networks:
  shared-net:
    name: cloud-project-net
    driver: bridge

services:
  # --- DATABASE RELAZIONALE ---
  mysql:
    image: mysql:8.0
    container_name: paymyseat-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymyseat_db
      MYSQL_USER: valeria
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - shared-net

  # --- DATABASE NOSQL
  mongodb:
    image: mongo:6.0
    container_name: paymyseat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-net

  # --- CACHE (Idempotenza) ---
  redis:
    image: redis:alpine
    container_name: paymyseat-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - shared-net

  # --- MESSAGE BROKER (Saga / Rimborso) ---
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: paymyseat-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared-net

  # --- MICROSERVIZI PYTHON/FLASK ---
  payment_api:
    build: 
      context: ./services/payment_api
    container_name: paymyseat-payment-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=valeria
      - MYSQL_PASSWORD=password
      - MYSQL_DB=paymyseat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - shared-net

  outbox_relay:
    build: 
      context: ./services/payment_api
    container_name: paymyseat-outbox-relay
    command: python outbox_relay.py
    restart: unless-stopped
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=valeria
      - MYSQL_PASSWORD=password
      - MYSQL_DB=paymyseat_db
      - RABBITMQ_HOST=rabbitmq
      - MONGO_HOST=mongodb
    depends_on:
      - mysql
      - rabbitmq
      - mongodb
    networks:
      - shared-net

  refund_worker:
    build: 
      context: ./services/refund_worker
    container_name: paymyseat-refund-worker
    restart: unless-stopped
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=valeria
      - MYSQL_PASSWORD=password
      - MYSQL_DB=paymyseat_db
      - RABBITMQ_HOST=rabbitmq
      - MONGO_HOST=mongodb
      - GATEWAY_URL=http://gateway_adapter:5002/api/gateway/charge
    depends_on:
      - mysql
      - rabbitmq
      - mongodb
    networks:
      - shared-net

  gateway_adapter:
    build: 
      context: ./services/gateway_adapter
    container_name: paymyseat-gateway
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - WEBHOOK_SECRET=${PAYMYSEAT_WEBHOOK_SECRET}
    depends_on:
      - rabbitmq
    networks:
      - shared-net

  # --- FRONTEND (React / Vite) ---
  frontend:
    build:
      context: ./frontend
    container_name: paymyseat-frontend
    restart: unless-stopped
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - payment_api
    networks:
      - shared-net

volumes:
  mysql_data:
    name: paymyseat-mysql-data
  mongo_data:
    name: paymyseat-mongo-data